### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by OoLunar** [IDoEverything/CustomRPC#1]
Can we have command line arguments for use on other operating systems? This would be beneficial for OSX or Linux

**Comment by CabbageAdi** [comment]
This is currently targeted at windows (therefore the use of winforms). I'll come back to this if I ever feel like adding support for other operating systems.

**Comment by CabbageAdi** [comment]
Now that my mind has been awakened to the wonders of Linux, support for command line arguments has been added, with instructions to run given in the readme. Thanks!
